function main() {
  return [
    {
      id: 10,
      name: "Kanban",
      path: "/kanban/index",
      icon: "icon-activity",
      rank: 10,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 20,
      name: "Material",
      path: "/table/material",
      icon: "icon-package",
      rank: 20,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: null,
    },
    {
      id: 30,
      name: "Plan",
      path: "/table/plan",
      icon: "icon-calendar",
      rank: 30,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 40,
      name: "Supplier",
      path: "/table/supplier",
      icon: "icon-book",
      rank: 40,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 50,
      name: "Warehouse",
      path: "/table/warehouse",
      icon: "icon-home",
      rank: 50,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 60,
      name: "User",
      path: "/table/user",
      icon: "icon-users",
      rank: 60,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 70,
      name: "Record",
      path: "/table/record.total",
      icon: "icon-archive",
      rank: 70,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 80,
      name: "Log",
      path: "/table/synclog",
      icon: "icon-clock",
      rank: 80,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 2010,
      name: "Material",
      path: "/table/material",
      icon: "icon-package",
      rank: 10,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 20,
    },
    {
      id: 2020,
      name: "SKU",
      path: "/table/material.sku",
      icon: "icon-package",
      rank: 20,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 20,
    },
    {
      id: 2030,
      name: "Stock",
      path: "/table/stock",
      icon: "icon-package",
      rank: 30,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 20,
    },
    {
      id: 2040,
      name: "Category",
      path: "/table/material.category",
      icon: "icon-package",
      rank: 40,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 20,
    },
    {
      id: 7009,
      name: "Records",
      path: "/table/record.total",
      icon: "icon-package",
      rank: 9,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 70,
    },
    {
      id: 7010,
      name: "Out Records",
      path: "/table/record.material.out",
      icon: "icon-package",
      rank: 10,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 70,
    },
    {
      id: 7020,
      name: "In Records",
      path: "/table/record.material.in",
      icon: "icon-package",
      rank: 20,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 70,
    },
    {
      id: 7030,
      name: "Enter",
      path: "/table/record.user.in",
      icon: "icon-package",
      rank: 30,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 70,
    },
    {
      id: 7040,
      name: "Leave",
      path: "/table/record.user.out",
      icon: "icon-package",
      rank: 30,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 70,
    },
  ];
}
